# permissions for end users to view reserves.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: reserve
    app.kubernetes.io/managed-by: kustomize
  name: pool-reserve-viewer-role
rules:
- apiGroups:
  - pool.w-h-a.io
  resources:
  - reserves
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pool.w-h-a.io
  resources:
  - reserves/status
  verbs:
  - get
